In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])               # 1D array
b = np.array([[1, 2], [3, 4]])        # 2D array

| Function                             | Description                         |
| ------------------------------------ | ----------------------------------- |
| `np.zeros(shape)`                    | Array filled with 0                 |
| `np.ones(shape)`                     | Array filled with 1                 |
| `np.eye(n)`                          | Identity matrix                     |
| `np.full(shape, val)`                | Filled with a specific value        |
| `np.arange(start, stop, step)`       | Like `range()`                      |
| `np.linspace(start, stop, num)`      | Evenly spaced values                |
| `np.random.rand(m, n)`               | Uniform distribution \[0,1)         |
| `np.random.randn(m, n)`              | Normal distribution (mean=0, std=1) |
| `np.random.randint(low, high, size)` | Random integers                     |


In [4]:
shape_x = [4, 1]
shape_y = [1, 4]

In [5]:
np.zeros(shape_x)

array([[0.],
       [0.],
       [0.],
       [0.]])

In [6]:
np.zeros(shape_y)

array([[0., 0., 0., 0.]])

In [7]:
np.ones(shape_x)

array([[1.],
       [1.],
       [1.],
       [1.]])

In [8]:
np.ones(shape_y)

array([[1., 1., 1., 1.]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.full(shape_y, 7)

array([[7, 7, 7, 7]])

In [11]:
np.full(shape_x, 7)

array([[7],
       [7],
       [7],
       [7]])

In [12]:
np.arange(start=0, stop=15, step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [13]:
np.linspace(0, 15, 5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [15]:
# Uniform distribution [0,1)
np.random.rand(1, 15)

array([[0.76721349, 0.57515248, 0.79340187, 0.92698533, 0.12606634,
        0.86286972, 0.90253316, 0.56609542, 0.24982883, 0.51855829,
        0.69378798, 0.1006268 , 0.93326364, 0.11394291, 0.12000728]])

In [16]:
# Normal distribution (mean=0, std=1)
np.random.randn(1, 15)

array([[-0.41557218, -0.0088557 , -0.65686774, -0.48254845,  0.35614775,
         0.40717352, -1.6119606 , -0.53538556,  0.6659154 , -0.68300212,
        -1.65985029, -1.60131747, -0.30157137, -1.39300703,  0.60295887]])

In [17]:
np.random.randint(10, 25, 5)

array([20, 21, 13, 10, 12])

In [24]:
a = np.array([5, 2, 3])               # 1D array
b = np.array([[21, 23, 46]])        # 2D array

In [25]:
np.add(a, b)

array([[26, 25, 49]])

In [26]:
np.subtract(a ,b)

array([[-16, -21, -43]])

In [27]:
np.multiply(a, b)

array([[105,  46, 138]])

In [28]:
np.divide(a, b)

array([[0.23809524, 0.08695652, 0.06521739]])

In [29]:
np.sqrt(a)

array([2.23606798, 1.41421356, 1.73205081])

In [30]:
np.exp(a)

array([148.4131591 ,   7.3890561 ,  20.08553692])

In [31]:
np.log(a)

array([1.60943791, 0.69314718, 1.09861229])

In [32]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.itemsize)

(3,)
1
3
int64
8


In [36]:
arr = b = np.array([[21, 23], [46, 79], [26, 90]]) # 2D array

arr.reshape(3,2)

array([[21, 23],
       [46, 79],
       [26, 90]])

In [37]:
arr.flatten()

array([21, 23, 46, 79, 26, 90])

In [38]:
arr.T

array([[21, 46, 26],
       [23, 79, 90]])

In [40]:
print(arr[1])         # Get element at index 1
print(arr[1:2])       # Get slice
print(arr[:, 1])      # Get second column
print(arr[0:2, 1:3])  # Get submatrix

[46 79]
[[46 79]]
[23 79 90]
[[23]
 [79]]


In [43]:
a = np.random.randint(low=5, high=70, size=7)
b = np.random.randint(low=15, high=90, size=7)

In [44]:
a.dot(b)           # Matrix multiplication

np.int64(7544)

In [50]:
a = np.array([5, 2, 3])               # 1D array
b = np.array([[21, 23], [46, 15], [37, 96]])        # 2D array

In [51]:
np.matmul(a, b)

array([308, 433])

In [54]:
b = np.array([[21, 23, 26], [46, 15, 57], [37, 96, 36]])        # 2D array

print(np.linalg.inv(b))   # Inverse
print(np.linalg.det(b))   # Determinant
print(np.linalg.eig(b)) 

[[-6.81874741e-01  2.30609706e-01  1.27333057e-01]
 [ 6.26296143e-02 -2.84805751e-02 -1.38255219e-04]
 [ 5.33803401e-01 -1.61067330e-01 -1.02723628e-01]]
7233.0000000000055
EigResult(eigenvalues=array([121.06904706,  -1.24933346, -47.81971361]), eigenvectors=array([[-0.32630264, -0.785426  , -0.07554985],
       [-0.55334986,  0.06383352, -0.63914221],
       [-0.76637492,  0.61565516,  0.76536884]]))


| Function         | Description        |
| ---------------- | ------------------ |
| `np.mean(arr)`   | Mean               |
| `np.median(arr)` | Median             |
| `np.std(arr)`    | Standard deviation |
| `np.sum(arr)`    | Sum                |
| `np.min(arr)`    | Minimum            |
| `np.max(arr)`    | Maximum            |
| `np.argmax(arr)` | Index of max       |
| `np.argmin(arr)` | Index of min       |
| `np.unique(arr)` | Unique values      |

In [58]:
print(np.mean(b))
print(np.median(b))
print(np.std(b))
print(np.sum(b))
print(np.min(b))
print(np.max(b))
print(np.argmin(b))
print(np.argmax(b))
print(np.unique(b))

39.666666666666664
36.0
23.466287875730725
357
15
96
4
7
[15 21 23 26 36 37 46 57 96]
