In [3]:
import numpy as np

In [6]:
a = np.array([1, 2, 3]) # it stores the list in type of ndarray
b = np.array([[1, 2], [3, 4]])

In [3]:
print(a)

[1 2 3]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(type(b))

<class 'numpy.ndarray'>


In [7]:
print(b)

[[1 2]
 [3 4]]


In [8]:
np.zeros([4,1])

array([[0.],
       [0.],
       [0.],
       [0.]])

In [10]:
shape_x = [4, 1]
shape_y = [1, 4]

In [12]:
np.zeros(shape_x)

array([[0.],
       [0.],
       [0.],
       [0.]])

In [17]:
np.zeros(shape_y)

array([[0., 0., 0., 0.]])

In [15]:
np.ones(shape_y)

array([[1., 1., 1., 1.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.full([1, 4], 7)

array([[7, 7, 7, 7]])

In [21]:
np.arange(start=0, stop=15, step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [23]:
np.linspace(0, 15, 5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [6]:
print(np.linspace(0, 5, 1))

[0.]


In [7]:
print(np.linspace(0, 5, 2))

[0. 5.]


In [4]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [5]:
print(np.linspace(0, 10, 12))

[ 0.          0.90909091  1.81818182  2.72727273  3.63636364  4.54545455
  5.45454545  6.36363636  7.27272727  8.18181818  9.09090909 10.        ]


In [26]:
np.random.rand(1, 15)

array([[0.49135312, 0.03331357, 0.07418979, 0.62100702, 0.95218233,
        0.55453989, 0.6733004 , 0.44352235, 0.28046657, 0.09743959,
        0.11335926, 0.97168883, 0.02819551, 0.87520197, 0.11741795]])

In [49]:
np.random.randn(1, 10)

array([[ 2.19021057, -0.09318368,  0.29308393, -1.59851281,  2.02303756,
         1.09309461,  1.76529421,  2.82218491,  0.91971701, -0.120473  ]])

In [27]:
np.random.randn(1, 15)

array([[-0.90839402, -0.7786137 ,  0.86486348,  2.02146956,  1.89603496,
        -0.36091954,  0.62925421,  1.77352829,  0.87045426,  1.42118995,
         0.84057049, -1.08280537,  1.88078112,  0.34404974,  1.58747848]])

In [28]:
np.random.randint(10, 25, 5)

array([19, 17, 11, 13, 10], dtype=int32)

In [29]:
a = np.array([5, 2, 3])
b = np.array([21, 23, 46])

In [30]:
np.add(a, b)

array([26, 25, 49])

In [31]:
np.subtract(b, a)

array([16, 21, 43])

In [32]:
np.multiply(a, b)

array([105,  46, 138])

In [34]:
np.divide(a, b)

array([0.23809524, 0.08695652, 0.06521739])

In [35]:
np.sqrt(a)

array([2.23606798, 1.41421356, 1.73205081])

In [36]:
np.exp(a)

array([148.4131591 ,   7.3890561 ,  20.08553692])

In [37]:
np.log(a)

array([1.60943791, 0.69314718, 1.09861229])

In [38]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.itemsize)

(3,)
1
3
int64
8


In [39]:
arr = b = np.array([[21, 23], [46, 79], [26, 90]]) # 2D array

arr.reshape(3,2)

array([[21, 23],
       [46, 79],
       [26, 90]])

In [40]:
arr.flatten()

array([21, 23, 46, 79, 26, 90])

In [41]:
arr.T # it transposes

array([[21, 46, 26],
       [23, 79, 90]])

In [42]:
# slicing 
print(arr[1])
print(arr[:, 1])
print(arr[0:2, 1:3])

[46 79]
[23 79 90]
[[23]
 [79]]


In [58]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 3])

In [53]:
b.dot(a)

np.int64(19)

In [54]:
a.dot(b)

np.int64(19)

In [59]:
a = np.array([5, 2, 3])
b = np.array([[21, 23], [46, 15], [37, 96]])

In [60]:
np.matmul(a, b)

array([308, 433])

In [63]:
b = np.array([[21, 23, 26], [46, 15, 57], [37, 96, 36]])

print(np.linalg.inv(b))   # Inverse
print(np.linalg.det(b))   # Determinant
print(np.linalg.eig(b)) 

[[-6.81874741e-01  2.30609706e-01  1.27333057e-01]
 [ 6.26296143e-02 -2.84805751e-02 -1.38255219e-04]
 [ 5.33803401e-01 -1.61067330e-01 -1.02723628e-01]]
7233.0000000000055
EigResult(eigenvalues=array([121.06904706,  -1.24933346, -47.81971361]), eigenvectors=array([[-0.32630264, -0.785426  , -0.07554985],
       [-0.55334986,  0.06383352, -0.63914221],
       [-0.76637492,  0.61565516,  0.76536884]]))
